### ISSUE TITLE
authorization error response

### ISSUE THREAD

**Issue by hatappi** [speee/ruboty-authorization#3]
ruboty exists `all` option.
if `all` option use, no prefix bot name.

when this plugin use, unauthorized user speak, ruboty reply `[user_name] is not authorized user`.
But sometimes reply in unintended speech.

<img width="393" alt="2016-10-15 18 51 26" src="https://cloud.githubusercontent.com/assets/3453977/19409121/683b2522-9308-11e6-80cf-65b8d97dcfaf.png">

**Comment by selmertsx** [comment]
This issue was solved by https://github.com/speee/ruboty-authorization/pull/4.
Thanks for your contribution!!
